name: FF Merge

on: 
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fast Forward PR
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"