name: FF Merge

on: 
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "${{ github.event.issue.pull_request }}"
          echo "${{ github.event.comment.body }}"
          echo "${{ github.event.pull_request }}"
          echo "${{ github.event.pull_request.number }}"
          echo "${{ github.event.review.body }}"
  ff-merge:
    runs-on: ubuntu-latest
    if: (github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')) || (github.event.pull_request != '' && contains(github.event.review.body, '/fast-forward'))
    steps:
      - name: Fast Forward
        run: |
          echo "Yay"